name: muelltrenninator
description: System for interacting with the “Mülltrenninator” project and a proxy for the AI worker.
publish_to: none
repository: https://github.com/Muelltrenninator/muelltrenninator

environment:
  sdk: ^3.9.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  gitbaker: ^0.1.2

workspace:
  - packages/muelltrenninator_server
  - packages/muelltrenninator_client
